### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by julianbrooks** [aragoncoop/DRtracer#1]
I'm not sure what a 'DR' is and represents?

Would it make sense to do this in 3box? Though am happy to try a number of options, esp if the info is easily transferable (by coords) rather than our members.

the above info we can add to the README

**Comment by sepu85** [comment]
Delegated Resource, is the name I'm choosing to refer to the resources receiving grants as per AGP-40, happy to use a different one if you or somebody else propose something better
